### PR TITLE
Upgrade to nan2

### LINKED ISSUE #63: Upgrade to Nan 2.x / Node v4/5
To support Node 4/5 we'll need to upgrade Nan and the code.

/cc @mikemorris

### PR DESCRIPTION
**Pull request by mikemorris**
For Node.js v4.x and v5.x support, fixes #63

### CODE REVIEW

**Comment by mikemorris** [comment]
Hitting errors that I think may stem from falsy comparisons somewhere, considering that [`should return color false for an existing tile`](https://github.com/mapbox/tilelive-s3/blob/7d99dbbb1a3e2165f61f59ac421aac37e31fdf9c/test/s3.test.js#L104-L110) is expected behavior. I'm also a bit surprised that tests are currently passing considering that no errors are actually thrown in `Decode` ([`TypeError` objects are created but nothing happens with them](https://github.com/mapbox/tilelive-s3/blob/7d99dbbb1a3e2165f61f59ac421aac37e31fdf9c/src/decode.cpp#L129-L143)).

**Comment by yhahn** [comment]
:disappointed: memory lane, here we go... @mikemorris will let you know if I see anything

**Comment by springmeyer** [comment]
> Buffer is changing between runs.

@yhahn likely because `Nan::NewBuffer` needs to instead be `Nan::CopyBuffer`. /cc @mikemorris

**Comment by mikemorris** [comment]
Ugh good catch @springmeyer, this was using [`NanNewBufferHandle`](https://github.com/nodejs/nan/tree/399b3a54ada39a7cf7a11978ea727eae3686666e#api_nan_new_buffer_handle) previously.

**Comment by yhahn** [comment]
:rice: :bow: thank you @mikemorris

**Pull request merged**
