### PR TITLE
Begin nan port

### PR DESCRIPTION
**Pull request by tmcw**
Current fails:

```
  CXX(target) Release/obj.target/tilelive_s3/src/decode.o
../src/decode.cpp:116:94: error: no member named 'handle_' in 'v8::Object'
            NanNew(Buffer::New((char*)baton->result, baton->resultLength, freeBuffer, NULL)->handle_),
                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ^
../src/decode.cpp:119:9: error: no member named 'Call' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
        TRY_CATCH_CALL(NanGetCurrentContext()->Global(), baton->callback, 3, argv);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/decode.hpp:55:16: note: expanded from macro 'TRY_CATCH_CALL'
    (callback).Call((context), (argc), (argv));                               \
    ~~~~~~~~~~ ^
../src/decode.cpp:132:9: error: no member named 'Call' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
        TRY_CATCH_CALL(NanGetCurrentContext()->Global(), baton->callback, 1, argv);
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../src/decode.hpp:55:16: note: expanded from macro 'TRY_CATCH_CALL'
    (callback).Call((context), (argc), (argv));                               \
    ~~~~~~~~~~ ^
../src/decode.cpp:179:35: error: no matching function for call to 'Data'
    image->data = (unsigned char*)node::Buffer::Data(image->buffer.As<Object>());
                                  ^~~~~~~~~~~~~~~~~~
/Users/tmcw/.node-gyp/0.12.4/src/node_buffer.h:40:19: note: candidate function not viable: no known conversion from 'Persistent<v8::Object>' to 'v8::Handle<v8::Value>' for 1st
      argument
NODE_EXTERN char* Data(v8::Handle<v8::Value> val);
                  ^
/Users/tmcw/.node-gyp/0.12.4/src/node_buffer.h:41:19: note: candidate function not viable: no known conversion from 'Persistent<v8::Object>' to 'v8::Handle<v8::Object>' for 1st
      argument
NODE_EXTERN char* Data(v8::Handle<v8::Object> val);
                  ^
../src/decode.cpp:180:25: error: no matching function for call to 'Length'
    image->dataLength = node::Buffer::Length(image->buffer.As<Object>());
                        ^~~~~~~~~~~~~~~~~~~~
/Users/tmcw/.node-gyp/0.12.4/src/node_buffer.h:42:20: note: candidate function not viable: no known conversion from 'Persistent<v8::Object>' to 'v8::Handle<v8::Value>' for 1st
      argument
NODE_EXTERN size_t Length(v8::Handle<v8::Value> val);
                   ^
/Users/tmcw/.node-gyp/0.12.4/src/node_buffer.h:43:20: note: candidate function not viable: no known conversion from 'Persistent<v8::Object>' to 'v8::Handle<v8::Object>' for 1st
      argument
NODE_EXTERN size_t Length(v8::Handle<v8::Object> val);
                   ^
5 errors generated.
```

### CODE REVIEW

**Comment by tmcw** [comment]
Would love words of wisdom on this last batch of errors which has been harder than the rest to bash through.

**Comment by mikemorris** [comment]
```
../src/decode.cpp:116:94: error: no member named 'handle_' in 'v8::Object'
```
https://github.com/nodejs/nan#api_nan_object_wrap_handle

```
../src/decode.cpp:119:9: error: no member named 'Call' in 'v8::Persistent<v8::Function, v8::NonCopyablePersistentTraits<v8::Function> >'
```
Check how these functions are assigned to `v8::Persistent`, use [`NanAssignPersistent`](https://github.com/nodejs/nan#nanassignpersistenthandle-object) if not doing that already.

```
candidate function not viable: no known conversion from 'Persistent<v8::Object>' to 'v8::Handle<v8::Object>' for 1st argument
```
This is a fun one. In newer versions of V8, [`v8::Persistent<T>` no longer inherits from `v8::Handle<T>`](https://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/). (Looks unrelated to your errors, but @tmpsantos found that although C++11 move semantics should work with STL containers, they're [not fully implemented](https://github.com/mapbox/node-mapbox-gl-native/commit/b602835626dfc1532bf5c26b9d2c34054a2d8fac)).

**Comment by springmeyer** [comment]
The port to nan is now done and the code compilers.

Two more things to do:

1) There is currently a failing test:

```
# should load the alpha mask for a tile
/home/travis/build/mapbox/tilelive-s3/node_modules/tape/index.js:75
        throw err
              ^
Error: Tile does not exist
```

But it looks like this is due to something changing upstream as I restarted a previously passing build in master and it now fails with the same error: https://travis-ci.org/mapbox/tilelive-s3/jobs/64978055


2) memory leak checking

Need to remove the dodgy use of `auto_ptr` and then run code through valgrind.

**Comment by springmeyer** [comment]
This is ready to merge code-wise. The failing tests (that I'm pretty sure are unrelated to this branch) however are actually preventing the `decoder.decode` path from running in the tests. @yhahn - would you be able to take a look at the tests in master to fix them there? Then I'll rebase this branch and make sure things are passing before merging.

**Comment by springmeyer** [comment]
@yhahn - noticed you merged fixes. Thanks! Seeing that fixed tests for node v0.10.x but not v0.12.x - so perhaps we've got a deeper tilelive.js node v0.12.x bug afoot. Just pushed https://travis-ci.org/mapbox/tilelive.js/builds/69963092 to see if tilelive.js tests pass with node v0.12.x.

**Comment by yhahn** [comment]
Ok -- I think at least one of the test fails on travis is related to the matrix -- the tests are putting objects to S3 and then checking them (and deleting previous runs) so I think they're tripping over each other when run in parallel.

Working on segmenting testruns by timestamp or so right now to disentangle.

**Comment by springmeyer** [comment]
I added node v12 testing in node-tilejson and the same errors happen: https://travis-ci.org/mapbox/node-tilejson/builds/70100324. So perhaps this needs to be fixed there?

**Comment by yhahn** [comment]
Next up:

- [ ] upstream tag/release of node-tilejson

**Comment by rclark** [comment]
#47 removes tilejson -- should we coordinate these two PRs?

**Comment by rclark** [comment]
Closing in favor of #48

**Pull request closed without merging**
